### ISSUE TITLE
login html instead of browser prompt

### ISSUE THREAD

**Issue by sudo77** [mmguero/nginx-ldap#1]
Hello,

I am currently working on integrating LDAP authentication into my Nginx configuration. However, I would like to customize the login experience by creating a dedicated login page, instead of using the default basic authentication prompt that Nginx provides.

Currently, when a user tries to access a protected resource, they are greeted with a browser login prompt. I would like to replace this prompt with a custom HTML login page where users can enter their credentials, which will then be validated via LDAP.

Current Setup:

I am using Nginx as a reverse proxy in front of a Flask application.
LDAP authentication is configured in Nginx using the auth_ldap directive.
I just want a login.html file with limple username and password which is running on the nginx-ldap container

can you help me, I dont get it running with the html file
with the login Prompt it is working so far

thanks

**Comment by mmguero** [comment]
sorry, that's not something i'm interested in doing in this repo. best of luck, though!
